#!/usr/bin/env python3
"""
Template for global censorship analysis.

This script illustrates how to compute global censorship metrics from
judge-scored model-response files. It assumes that each model file contains
prompt-level judge scores for the same set of prompts, and that a separate
uncensored reference set is available for estimating the uncensored baseline.

The original experiments used the same analysis structure with model-specific
score files generated by the response-generation and judge-scoring pipeline.
"""

from __future__ import annotations

import argparse
import json
import os
from typing import Dict, List, Optional

import pandas as pd

from framework_utils import (
    load_df,
    fit_judge_calibration,
    apply_judge_calibration,
    load_and_score_model_datasets,
    build_filtered_score_matrix,
    analyze_global_censorship,
)


def load_model_paths(path: str) -> Dict[str, str]:
    """
    Load a JSON file mapping model names to judge-scored dataset paths.

    Example JSON:
    {
        "model_a": "data/model_scores/model_a_scores.csv",
        "model_b": "data/model_scores/model_b_scores.csv"
    }
    """
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def parse_list_arg(value: Optional[str]) -> Optional[List[str]]:
    """
    Parse a comma-separated list argument.
    """
    if value is None or value.strip() == "":
        return None
    return [x.strip() for x in value.split(",") if x.strip()]


def main() -> None:
    parser = argparse.ArgumentParser(description="Run global censorship analysis.")

    parser.add_argument(
        "--model_paths_json",
        type=str,
        required=True,
        help="JSON file mapping model names to judge-scored dataset paths.",
    )
    parser.add_argument(
        "--calib_file",
        type=str,
        required=True,
        help="Calibration set with judge-score columns.",
    )
    parser.add_argument(
        "--uncensored_file",
        type=str,
        required=True,
        help="Uncensored reference set used to estimate the baseline c.",
    )
    parser.add_argument(
        "--output_file",
        type=str,
        default="outputs/global_results.csv",
        help="Path to save global censorship results.",
    )

    parser.add_argument("--prompt_col", type=str, default="Prompt")
    parser.add_argument("--category_col", type=str, default="Category")
    parser.add_argument("--sub_category_col", type=str, default="Sub_Category")

    parser.add_argument(
        "--judge_score_cols",
        type=str,
        default="judge_claude_score,judge_gpt54_score,judge_grok_score",
        help="Comma-separated judge score columns.",
    )
    parser.add_argument(
        "--target_subcategories",
        type=str,
        default=None,
        help="Optional comma-separated list of subcategories/topics to evaluate. "
             "If omitted, all subcategories in the reference dataset are used.",
    )

    parser.add_argument("--tau_g", type=float, default=0.20)
    parser.add_argument("--tau_pi", type=float, default=0.60)
    parser.add_argument("--delta_eq", type=float, default=0.10)

    args = parser.parse_args()

    os.makedirs(os.path.dirname(args.output_file) or ".", exist_ok=True)

    model_paths = load_model_paths(args.model_paths_json)
    judge_score_cols = parse_list_arg(args.judge_score_cols)
    target_subcategories = parse_list_arg(args.target_subcategories)

    if not judge_score_cols:
        raise ValueError("At least one judge score column must be provided.")

    # 1. Fit judge calibration on the calibration set.
    calib_df = load_df(args.calib_file)
    calib_params = fit_judge_calibration(calib_df, judge_score_cols)

    # 2. Estimate uncensored baseline using the separate uncensored set.
    uncensored_df = load_df(args.uncensored_file)
    uncensored_df_scored = apply_judge_calibration(
        uncensored_df,
        judge_score_cols,
        calib_params,
    )
    baseline_c = uncensored_df_scored["s_b"].dropna().median()

    # 3. Load and calibrate all model datasets.
    scored_model_dfs = load_and_score_model_datasets(
        model_paths,
        judge_score_cols,
        calib_params,
    )

    # 4. Use one model dataset as metadata source.
    reference_df = list(scored_model_dfs.values())[0]

    if args.sub_category_col not in reference_df.columns:
        raise ValueError(
            f"Column '{args.sub_category_col}' not found in reference dataset. "
            "Use --sub_category_col to set the correct column name."
        )

    # 5. Determine topics/subcategories.
    if target_subcategories is None:
        subcategories = sorted(reference_df[args.sub_category_col].dropna().unique())
    else:
        subcategories = target_subcategories

    rows = []

    # 6. Run global censorship analysis for each topic/subcategory.
    for subcat in subcategories:
        score_matrix = build_filtered_score_matrix(
            scored_model_dfs,
            reference_df=reference_df,
            prompt_col=args.prompt_col,
            score_col="s_b",
            category=None,
            sub_category=subcat,
            category_col=args.category_col,
            sub_category_col=args.sub_category_col,
        )

        if score_matrix.empty:
            print(f"Skipping topic '{subcat}': empty score matrix.")
            continue

        res = analyze_global_censorship(
            score_matrix,
            baseline_c=baseline_c,
            tau_g=args.tau_g,
            tau_pi=args.tau_pi,
            delta_eq=args.delta_eq,
        )

        rows.append({
            "Topic": subcat,
            "n_prompts": res["n_prompts"],
            "baseline_c": res["baseline_c"],
            "mean_delta": res["mean_delta"],
            "pi_plus": res["pi_plus"],
            "fraction_models_censored": res["fraction_models_censored"],
            "wilcoxon_pvalue": res["wilcoxon_pvalue"],
            "tost_pvalue": res["tost_pvalue"],
            "equivalent_to_uncensored": res["equivalent_to_uncensored"],
            "ci90_low": res["ci90_low"],
            "ci90_high": res["ci90_high"],
            "global_censorship": res["global_censorship"],
        })

    results_df = pd.DataFrame(rows)
    results_df.to_csv(args.output_file, index=False)

    print(f"Saved global censorship results to: {args.output_file}")


if __name__ == "__main__":
    main()